# Generated by Django 3.1.3 on 2020-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='CHANGEME', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
